# Gateway - Pets
GET http://localhost:4000/api/pets

# Gateway - Adoptions
GET http://localhost:4000/api/adoptions

# Gateway - SPA
GET http://localhost:4000/


# Pets - Get
GET http://localhost:3100/api/pets

# Pets - Get location=Plett
GET http://localhost:3100/api/pets?location=office

# Pets - Add
POST http://localhost:3100/api/pets
Content-Type: application/json

{"name": "Fido", "location": "test"}

# Pets - Change status
PATCH http://localhost:3100/api/pets/994e1d3d-9243-4636-8286-bac667b3fdbb
content-type: application/json

{"status": "adopted"}


# Gateway - Adoptions add
POST http://localhost:4000/api/adoptions
content-type: application/json

{"pets": ["a", "b"], "location": "test"}

# Adoptions - Get location=Plett
GET http://localhost:4000/api/adoptions?location=Plett

# Adoptions - Change status
PATCH http://localhost:3200/api/adoptions/a1760fb5-ad6b-4794-9aa0-1c60fdf3e226
content-type: application/json

{"status": "approved"}
