FROM node:16-alpine 

RUN mkdir -p /srv
WORKDIR /srv

# Install before copying over source. Speeds up docker builds
COPY pets/package.json /srv/
COPY pets/yarn.lock /srv/
RUN yarn 

# Files
COPY lib /lib
COPY pets /srv

# Runtime
ENV NODE_PORT=80
EXPOSE 80
CMD node index.js
