FROM node:16-alpine 

RUN mkdir -p /srv
WORKDIR /srv

# Install before copying over source. Speeds up docker builds
COPY adoptions/package.json /srv/
COPY adoptions/yarn.lock /srv/
RUN yarn 

# Install deps found in lib
COPY lib/package.json /lib/
COPY lib/yarn.lock /lib/
RUN cd /lib && yarn

# Files
COPY lib /lib
COPY adoptions /srv

# Runtime
ENV NODE_PORT=80
EXPOSE 80
CMD node index.js
